### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Twor** [coderplanets/coderplanets_server#109]
https://twitter.com/i/status/1091198484617678848

**Comment by mydearxym** [comment]
@Twor 非常感谢反馈

在 viewer 打开的时候切换 community 会导致 crash, 这确实是个 Bug , 我会尽快修复.

**Comment by mydearxym** [comment]
this is front-end bug, fixed in  https://github.com/coderplanets/coderplanets_web/commit/3943484512b2aa53cb383230a008cd073ab253dc
